### ISSUE TITLE
Create an application-level sidebar

### ISSUE THREAD

**Issue by BobbyRadford** [BobbyRadford/jalapeno#4]
We need to have a sidebar for the application. The sidebar will contain navigation links depending on the context of the application.

**Comment by lucaswalter** [comment]
I can do this one. Do you have any pictures or example websites of sidebars that you like?

**Comment by lucaswalter** [comment]
Check this out: http://stackoverflow.com/questions/8625829/design-pattern-for-side-bar-with-dynamic-content-in-rails

There are a number of very good comments and suggestions for how to go about doing this. After looking through some of the comments, I think that the content_for () suggestion will fit us the best. With this pattern we will be able to have unique links displayed for each controller action.

**Comment by BobbyRadford** [comment]
@lucaswalter I don't have a particular design in mind ATM, but there are a few things I can think of off the top of my head that it will need.
### Sidebar Content
- [ ] Links for seeing rolls from different machines
- [ ] [badges](http://getbootstrap.com/components/#badges) showing rolls in various states
- [ ] filtering options for tables

There will indubitably be more on the sidebar, but you can start with this and add additional content in separate git commits as you see fit.
