### ISSUE TITLE
Create an application-level navigation bar

### ISSUE THREAD

**Issue by BobbyRadford** [BobbyRadford/jalapeno#5]
The navigation bar should contain links for returning to the application root and rolls, clothing and machines views. There should also be an indication of the currently authenticated user with a dropdown to sign out or take you to the user details view.

**Comment by lucaswalter** [comment]
The code I added for the dynamic changes clashed a bit with the existing navbar on the top of the page. When you get a chance, could you take a look at the new navbar in my feature branch and let me know what you think?
